// Namespace Configuration Values
export const SYMBAROUM = {};

SYMBAROUM.itemSortOrder = [
    "ability",
    "trait",
    "mysticalPower",
    "ritual",
    "boon",
    "burden",
    "armor",
    "weapon",
    "equipment",
    "artifact"
];

// Ability definitions
SYMBAROUM.abilitiesList = {
    "none": 'ABILITY_LABEL.DEFAULT', 
    "acrobatics": 'ABILITY_LABEL.ACROBATICS', 
    "alchemy": 'ABILITY_LABEL.ALCHEMY', 
    "agilecombat": 'ABILITY_LABEL.AGILE_COMBAT', 
    "armoredmystic": 'ABILITY_LABEL.ARMORED_MYSTIC', 
    "arrowjab": 'ABILITY_LABEL.ARROW_JAB', 
    "artifactcrafting": 'ABILITY_LABEL.ARTIFACT_CRAFTING', 
    "axeartist": 'ABILITY_LABEL.AXE_ARTIST', 
    "backstab": 'ABILITY_LABEL.BACKSTAB', 
    "beastlore": 'ABILITY_LABEL.BEAST_LORE', 
    "berserker": 'ABILITY_LABEL.BERSERKER', 
    "blacksmith": 'ABILITY_LABEL.BLACKSMITH', 
    "bloodcombat": 'ABILITY_LABEL.BLOOD_COMBAT', 
    "bodyguard": 'ABILITY_LABEL.BODYGUARD', 
    "channeling": 'ABILITY_LABEL.CHANNELING', 
    "cheapshot": 'ABILITY_LABEL.CHEAP_SHOT', 
    "dominate": 'ABILITY_LABEL.DOMINATE', 
    "ensnare": 'ABILITY_LABEL.ENSNARE', 
    "equestrian": 'ABILITY_LABEL.EQUESTRIAN', 
    "exceptionalattribute": 'ABILITY_LABEL.EX_ATTRIBUTE', 
    "featofstrength": 'ABILITY_LABEL.FEAT_STRENGTH', 
    "feint": 'ABILITY_LABEL.FEINT', 
    "flailer": 'ABILITY_LABEL.FLAILER', 
    "hammerrhythm": 'ABILITY_LABEL.HAMMER_RHYTHM', 
    "huntersinstinct": 'ABILITY_LABEL.HUNTER_INSTINCT', 
    "ironfist": 'ABILITY_LABEL.IRON_FIST', 
    "knifeplay": 'ABILITY_LABEL.KNIFE_PLAY', 
    "leader": 'ABILITY_LABEL.LEADER', 
    "loremaster": 'ABILITY_LABEL.LOREMASTER', 
    "manatarms": 'ABILITY_LABEL.MAN-AT-ARMS', 
    "mantledance": 'ABILITY_LABEL.MANTLE_DANCE', 
    "marksman": 'ABILITY_LABEL.MARKSMAN', 
    "medicus": 'ABILITY_LABEL.MEDICUS', 
    "naturalwarrior": 'ABILITY_LABEL.NATURAL_WARRIOR', 
    "opportunist": 'ABILITY_LABEL.OPPORTUNIST', 
    "poisoner": 'ABILITY_LABEL.POISONER', 
    "polearmmastery": 'ABILITY_LABEL.POLEARM_MASTERY', 
    "pyrotechnics": 'ABILITY_LABEL.PYROTECHNICS', 
    "quickdraw": 'ABILITY_LABEL.QUICK_DRAW', 
    "rapidfire": 'ABILITY_LABEL.RAPID_FIRE', 
    "rapidreflexes": 'ABILITY_LABEL.RAPID_REFLEXES', 
    "recovery": 'ABILITY_LABEL.RECOVERY', 
    "ritualist": 'ABILITY_LABEL.RITUALIST', 
    "runetattoo": 'ABILITY_LABEL.RUNE_TATTOO', 
    "shieldfighter": 'ABILITY_LABEL.SHIELD_FIGHTER', 
    "siegeexpert": 'ABILITY_LABEL.SIEGE_EXPERT', 
    "sixthsense": 'ABILITY_LABEL.SIXTH_SENSE', 
    "sorcery": 'ABILITY_LABEL.SORCERY', 
    "stafffighting": 'ABILITY_LABEL.STAFF_FIGHTING', 
    "staffmagic": 'ABILITY_LABEL.STAFF_MAGIC', 
    "steadfast": 'ABILITY_LABEL.STEADFAST', 
    "steelthrow": 'ABILITY_LABEL.STEEL_THROW', 
    "strangler": 'ABILITY_LABEL.STRANGLER', 
    "stronggift": 'ABILITY_LABEL.STRONG_GIFT', 
    "swordsaint": 'ABILITY_LABEL.SWORD_SAINT', 
    "symbolism": 'ABILITY_LABEL.SYMBOLISM', 
    "tactician": 'ABILITY_LABEL.TACTICIAN', 
    "theurgy": 'ABILITY_LABEL.THEURGY', 
    "trapper": 'ABILITY_LABEL.TRAPPER', 
    "trickarchery": 'ABILITY_LABEL.TRICK_ARCHERY', 
    "trollsinging": 'ABILITY_LABEL.TROLL_SINGING', 
    "twinattack": 'ABILITY_LABEL.TWIN_ATTACK', 
    "twohandedforce": 'ABILITY_LABEL.2HANDED_FORCE', 
    "witchcraft": 'ABILITY_LABEL.WITCHCRAFT', 
    "witchsight": 'ABILITY_LABEL.WITCHSIGHT', 
    "wizardry": 'ABILITY_LABEL.WIZARDRY', 
    "whipfighter": 'ABILITY_LABEL.WHIPFIGHTER', 
    "wrestling": 'ABILITY_LABEL.WRESTLING', 
    "twohandedfinesse": 'ABILITY_LABEL.2HANDED_FINESSE', 
    "blessings": 'ABILITY_LABEL.BLESSINGS'
};

SYMBAROUM.powersList = {
    "none": 'ABILITY_LABEL.DEFAULT', 
    "anathema": 'POWER_LABEL.ANATHEMA', 
    "banishingseal": 'POWER_LABEL.BANISHING_SEAL', 
    "bendwill": 'POWER_LABEL.BEND_WILL', 
    "blackbolt": 'POWER_LABEL.BLACK_BOLT', 
    "blackbreath": 'POWER_LABEL.BLACK_BREATH', 
    "blessedshield": 'POWER_LABEL.BLESSED_SHIELD', 
    "blindingsymbol": 'POWER_LABEL.BLINDING_SYMBOL', 
    "brimstonecascade": 'POWER_LABEL.BRIMSTONE_CASCADE', 
    "combathymn": 'POWER_LABEL.COMBAT_HYMN', 
    "confusion": 'POWER_LABEL.CONFUSION', 
    "curse": 'POWER_LABEL.CURSE', 
    "dancingweapon": 'POWER_LABEL.DANCING_WEAPON', 
    "drainingglyph": 'POWER_LABEL.DRAINING_GLYPH', 
    "entanglingvines": 'POWER_LABEL.ENTANGLING_VINES', 
    "exorcize": 'POWER_LABEL.EXORCIZE', 
    "firesoul": 'POWER_LABEL.FIRE_SOUL', 
    "flamewall": 'POWER_LABEL.FLAME_WALL', 
    "heroichymn": 'POWER_LABEL.HEROIC_HYMN', 
    "holyaura": 'POWER_LABEL.HOLY_AURA', 
    "illusorycorrection": 'POWER_LABEL.ILLUSORY_CORRECTION', 
    "inheritwound": 'POWER_LABEL.INHERIT_WOUND', 
    "larvaeboils": 'POWER_LABEL.LARVAE_BOILS', 
    "layonhands": 'POWER_LABEL.LAY_ON_HANDS', 
    "levitate": 'POWER_LABEL.LEVITATE', 
    "lifegiver": 'POWER_LABEL.LIFEGIVER', 
    "maltransformation": 'POWER_LABEL.MALTRANSFORMATION', 
    "mindthrow": 'POWER_LABEL.MIND-THROW', 
    "mirroring": 'POWER_LABEL.MIRRORING', 
    "naturesembrace": 'POWER_LABEL.NATURES_EMBRACE', 
    "priosburningglass": 'POWER_LABEL.PRIOS_BURNING_GLASS', 
    "protectiverunes": 'POWER_LABEL.PROTECTIVE_RUNES', 
    "psychicthrust": 'POWER_LABEL.PSYCHIC_THRUST', 
    "purgatory": 'POWER_LABEL.PURGATORY', 
    "retribution": 'POWER_LABEL.RETRIBUTION', 
    "revenantstrike": 'POWER_LABEL.REVENANT_STRIKE', 
    "shapeshift": 'POWER_LABEL.SHAPESHIFT', 
    "sphere": 'POWER_LABEL.SPHERE', 
    "spiritwalk": 'POWER_LABEL.SPIRIT_WALK', 
    "staffprojectile": 'POWER_LABEL.STAFF_PROJECTILE', 
    "stormarrow": 'POWER_LABEL.STORM_ARROW', 
    "teleport": 'POWER_LABEL.TELEPORT', 
    "thorncloak": 'POWER_LABEL.THORN_CLOAK', 
    "tormentingspirits": 'POWER_LABEL.TORMENTING_SPIRITS', 
    "trueform": 'POWER_LABEL.TRUE_FORM', 
    "unholyaura": 'POWER_LABEL.UNHOLY_AURA', 
    "unnoticeable": 'POWER_LABEL.UNNOTICEABLE', 
    "weakeninghymn": 'POWER_LABEL.WEAKENING_HYMN', 
    "wildhunt": 'POWER_LABEL.WILD_HUNT', 
    "battlesymbol": 'POWER_LABEL.BATTLE_SYMBOL', 
    "earthbinding": 'POWER_LABEL.EARTH_BINDING', 
    "markoftorment": 'POWER_LABEL.MARK_OF_TORMENT', 
    "serenity": 'POWER_LABEL.SERENITY', 
    "earthshot": 'POWER_LABEL.EARTH_SHOT', 
    "witchhammer": 'POWER_LABEL.WITCH_HAMMER'
};

SYMBAROUM.traitsList = {
    "acidicattack": 'TRAIT_LABEL.ACIDICATTACK', 
    "acidicblood": 'TRAIT_LABEL.ACIDICBLOOD', 
    "alternativedamage": 'TRAIT_LABEL.ALTERNATIVEDAMAGE', 
    "amphibian": 'TRAIT_LABEL.AMPHIBIAN', 
    "armored": 'TRAIT_LABEL.ARMORED', 
    "avengingsuccessor": 'TRAIT_LABEL.AVENGINGSUCCESSOR', 
    "bloodlust": 'TRAIT_LABEL.BLOODLUST', 
    "carapace": 'TRAIT_LABEL.CARAPACE', 
    "collectivepower": 'TRAIT_LABEL.COLLECTIVEPOWER', 
    "colossal": 'TRAIT_LABEL.COLOSSAL', 
    "companions": 'TRAIT_LABEL.COMPANIONS', 
    "corruptingattack": 'TRAIT_LABEL.CORRUPTINGATTACK', 
    "corruptionhoarder": 'TRAIT_LABEL.CORRUPTIONHOARDER', 
    "corruptionsensitive": 'TRAIT_LABEL.CORRUPTIONSENSITIVE', 
    "crushingembrace": 'TRAIT_LABEL.CRUSHINGEMBRACE', 
    "deadlybreath": 'TRAIT_LABEL.DEADLYBREATH', 
    "deathstruggle": 'TRAIT_LABEL.DEATHSTRUGGLE', 
    "devour": 'TRAIT_LABEL.DEVOUR', 
    "diminutive": 'TRAIT_LABEL.DIMINUTIVE', 
    "enthrall": 'TRAIT_LABEL.ENTHRALL', 
    "earthbound": 'TRAIT_LABEL.EARTHBOUND', 
    "freespirit": 'TRAIT_LABEL.FREESPIRIT', 
    "grapplingtongue": 'TRAIT_LABEL.GRAPPLINGTONGUE', 
    "gravelycold": 'TRAIT_LABEL.GRAVELYCOLD', 
    "harmfulaura": 'TRAIT_LABEL.HARMFULAURA', 
    "haunting": 'TRAIT_LABEL.HAUNTING', 
    "infectious": 'TRAIT_LABEL.INFECTIOUS', 
    "infestation": 'TRAIT_LABEL.INFESTATION', 
    "invisibility": 'TRAIT_LABEL.INVISIBILITY', 
    "leap": 'TRAIT_LABEL.LEAP', 
    "lifesense": 'TRAIT_LABEL.LIFESENSE', 
    "manifestation": 'TRAIT_LABEL.MANIFESTATION', 
    "many-headed": 'TRAIT_LABEL.MANYHEADED', 
    "metamorphosis": 'TRAIT_LABEL.METAMORPHOSIS', 
    "mysticalresistance": 'TRAIT_LABEL.MYSTICALRESISTANCE', 
    "naturalweapon": 'TRAIT_LABEL.NATURALWEAPON', 
    "nightperception": 'TRAIT_LABEL.NIGHTPERCEPTION', 
    "observant": 'TRAIT_LABEL.OBSERVANT', 
    "paralyzingvenom": 'TRAIT_LABEL.PARALYZINGVENOM', 
    "piercingattack": 'TRAIT_LABEL.PIERCINGATTACK', 
    "poisonous": 'TRAIT_LABEL.POISONOUS', 
    "poisonspit": 'TRAIT_LABEL.POISONSPIT', 
    "prehensileclaws": 'TRAIT_LABEL.PREHENSILECLAWS', 
    "rampage": 'TRAIT_LABEL.RAMPAGE', 
    "regeneration": 'TRAIT_LABEL.REGENERATION', 
    "robust": 'TRAIT_LABEL.ROBUST', 
    "rootwall": 'TRAIT_LABEL.ROOTWALL', 
    "shapeshifter": 'TRAIT_LABEL.SHAPESHIFTER', 
    "spiritform": 'TRAIT_LABEL.SPIRITFORM', 
    "sturdy": 'TRAIT_LABEL.STURDY', 
    "summoner": 'TRAIT_LABEL.SUMMONER', 
    "survivalinstinct": 'TRAIT_LABEL.SURVIVALINSTINCT', 
    "swarm": 'TRAIT_LABEL.SWARM', 
    "swift": 'TRAIT_LABEL.SWIFT', 
    "terrify": 'TRAIT_LABEL.TERRIFY', 
    "tunneler": 'TRAIT_LABEL.TUNNELER', 
    "undead": 'TRAIT_LABEL.UNDEAD', 
    "web": 'TRAIT_LABEL.WEB', 
    "wings": 'TRAIT_LABEL.WINGS', 
    "wisdomages": 'TRAIT_LABEL.WISDOM_AGES', 
    "wrecker": 'TRAIT_LABEL.WRECKER'
};


